version: '3'
services:
  emby_notifier:
    image: codenametest/emby_notifier_webui:latest
    container_name: emby_notifier
    environment:
      - TZ=Asia/Shanghai
      - WEB_PORT=5000
      - DB_PATH=/data/emby_notifier.db
    volumes:
      - emby_data:/data
    network_mode: "host"
    restart: unless-stopped

volumes:
  emby_data:
